const MAX_TAGS = 5
const MAX_GROUPS = 5
const MAX_COLORS = 5
const MAX_NAME_CHARACTERS = 25
const MAX_COLOR_NAME_CHARACTERS = 20

const limits = {
  MAX_COLORS,
  MAX_TAGS,
  MAX_GROUPS,
  MAX_NAME_CHARACTERS,
  MAX_COLOR_NAME_CHARACTERS
}

export default limits
